# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/exec_module.vh}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/temp_wires.vh}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/exec_zero.vh}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/exec_matrix_compiled.vh}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/core.vh}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/globals.vh}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/coremodules.vh}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/exec_module.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/temp_wires.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/exec_zero.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/exec_matrix_compiled.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/core.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/globals.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/coremodules.vh}}]
read_mem {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/new/data.mem}}
read_verilog -library xil_defaultlib {
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/imports/hdl/PS2Receiver.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/address_latch.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/address_mux.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/address_pins.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_bit_select.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_control.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_core.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_flags.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_mux_2.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_mux_2z.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_mux_3z.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_mux_4.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_mux_8.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_prep_daa.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_select.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_shifter_core.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/alu_slice.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/bus_control.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/bus_switch.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/clk_delay.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/imports/new/clockDiv.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/control_pins_n.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/data_pins.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/data_switch.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/data_switch_mask.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/imports/hdl/debouncer.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/decode_state.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/execute.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/new/gamepongrgb.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/inc_dec.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/inc_dec_2bit.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/interrupts.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/ir.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/new/mem_mapped_keyboard.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/memory_ifc.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/pin_control.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/new/pixelSegment.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/pla_decode.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/imports/new/quadSevenSeg.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/reg_control.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/reg_file.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/reg_latch.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/resets.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/new/screenrom.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/imports/new/segmentDecoder.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/sequencer.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/new/vga_sync.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/new/whichSegment.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/imports/x/z80_top_direct_n.v}
  {C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/sources_1/new/z80_tester.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/constrs_1/new/Basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Sawaphob Chavana/Desktop/ponggame_finalproject/Ponggame.srcs/constrs_1/new/Basys3.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top z80_tester -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef z80_tester.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file z80_tester_utilization_synth.rpt -pb z80_tester_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
